Alt-Org/Altzone-Server

- src/authorization/authorization.interceptor.ts
- src/characterClass/characterClass.controller.ts
- src/common/service/basicService/BasicService.ts
1.
The bug was related to AuthorizationInterceptor class getAllowedFields() method identifying allowedFields wrong. 
It was returning only "objectType" field in case there are no allowed fields specified in the authorization rules.
2.
Additionally bugs in BasicService were found and fixed related to options parameters not being destructured  properly
Closes #104
> fix bug with @AddType() overriding object fields

- src/authorization/rule/playerRules.ts
- src/chat/chat.controller.ts
- src/common/interceptor/request/offsetPagination.interceptor.ts
1. Fix bug with /player GET not returning clan_id field. It was due to clan_id was not included as public field in player authorization rules
2. Fix bug with /chat GET returning Server error. It was due to improper data parsing in the @OffsetPaginate() interceptor. If data was a Promise it was not awaited and later the interceptor was trying to access properties of this promise, which were not exist
Closes #124
> Fix bug with /player GET and /chat GET

- docker-compose.yml
- mosquitto/config/aclfile.conf
- mosquitto/config/mosquitto.conf
- mosquitto/config/password_1
- nginx.conf
- prod_docker-compose.yml
1. Add MQTT broker setup
2. Add basic authentication
3. Add list of trusted publishers
I did not manage to make the WSS work togher with MQTT and move it to separate Issue
> Add MQTT broker setup

- src/test/common/decorator/response/ExtractField.test.ts
- src/test/common/decorator/response/FormatAPIResponse.test.ts
- src/test/common/decorator/response/UniformResponse.test.ts
1. tests for ExtractField() decorator
> add tests for ExtractField() decorator

- src/test/common/decorator/response/UniformResponse.test.ts
1. tests for UniformResponse decorator
> add tests for UniformResponse decorator

- src/test/common/decorator/response/FormatAPIResponse.test.ts
- src/test/common/decorator/response/UniformResponse.test.ts
1. add tests for FormatAPIResponse() decorator
> add tests for FormatAPIResponse() decorator

- src/__tests__/clan/modules/clanCommon.ts
- src/dailyTasks/dailyTasks.module.ts
- src/rewarder/rewarder.module.ts
1. Remove unnecessary dependency of `RewarderModule` from `DailyTasksModule` and so resolve circular dependency between ClanModule and RewarderModule
2. Add `DailyTasks` module injection to clan testing module to fix failing tests
> Fix failing tests after 09.02.2025 release

- src/app.module.ts
- src/box/box.controller.ts
- src/box/box.module.ts
- src/box/box.service.ts
- src/box/dto/box.dto.ts
- src/box/dto/createBox.dto.ts
- src/box/dto/updateBox.dto.ts
- src/box/enum/BoxReference.enum.ts
- src/box/enum/SessionStage.enum.ts
- src/box/schemas/box.schema.ts
- src/box/schemas/groupAdmin.schema.ts
- src/box/schemas/tester.schema.ts
- src/common/enum/modelName.enum.ts
1. Schemas for the box module
2. DTOs for the box module
3. skeleton classes for box module
> Add skeleton of box module

- src/box/box.service.ts
This pull request includes a small change to the `BoxService` class in the `src/box/box.service.ts` file. The change adds the `box_id` to the payload of the JWT token.
* [`src/box/box.service.ts`](diffhunk://#diff-8bf43102f5c273643f01c13636469c8020763bd83535865026637de5933798e8R95): Added `box_id` to the JWT token payload in the `BoxService` class.
> feat(BoxService): include box_id in JWT access token payload

- src/__tests__/box/modules/box.module.ts
- src/__tests__/box/modules/boxCommon.ts
- src/__tests__/box/tester/PasswordGenerator/generatePassword.test.ts
- src/box/box.module.ts
- src/box/tester/passwordGenerator.ts
The `PasswordGenerator` class generates passwords, which is easier to remember and read for a human
- Add `PasswordGenerator` class
- Add `generatePassword()` method, which can generate two types of passwords. One type is a "sentence", which will generate something like _koira-syö-makkaraa_ or "place" type, such as _iso-karhu-keittiössä_
- Add unit tests for the `generatePassword()` method
> Add PasswordGenerator class to generate user readable passwords

- src/__tests__/box/modules/box.module.ts
- src/__tests__/box/modules/boxCommon.ts
- src/__tests__/box/tester/TesterService/addTestersToBox.test.ts
- src/__tests__/box/tester/TesterService/addTestersToClans.test.ts
- src/__tests__/box/tester/TesterService/createTesters.test.ts
- src/__tests__/box/tester/TesterService/deleteTesters.test.ts
- src/box/box.module.ts
- src/box/tester/dto/define.testers.dto.ts
- src/box/tester/tester.controller.ts
- src/box/tester/tester.service.ts
The endpoint _/box/testers_ POST was added, where the amount of testers can be defined. The amount of testers can be increased or decreased. Additionally for each tester in the box a profile and player objects are created / removed, and the player objects are automatically and evenly assigned / removed  in one of box clans.
Notice that in order to be able to use this endpoint the user should be an admin of this box and the box should be already initialized.
- Added _/box/testers_ POST endpoint
- Added tests for the `TesterService` class
Closes #417
> Endpoint for defining amount of testers in the box

- src/__tests__/box/BoxService/deleteBox.test.ts
- src/box/box.controller.ts
- src/box/box.service.ts
- src/box/tester/tester.service.ts
Added endpoint for deleting the box and group admin and all associated data.
Added tests for the deleteBox service method.
- Added /delete endpoint the the box controller
- Added deleteBox service method for box service
- Added unit tests for the deleteBox method
- Fixed the issue in tester.service.ts createPlayers method where the explicit return type did not match the actual one.
> Added endpoint for deleting testing box data

- src/__tests__/box/SessionStarterService/start.test.ts
- src/__tests__/box/modules/box.module.ts
- src/__tests__/box/modules/boxCommon.ts
- src/__tests__/dailyTasks/data/dailyTaskBuilderFactory.ts
- src/__tests__/dailyTasks/data/dailyTasks/DailyTaskBuilder.ts
- src/__tests__/dailyTasks/modules/dailyTasks.module.ts
- src/__tests__/dailyTasks/modules/dailyTasksCommon.module.ts
- src/box/box.controller.ts
- src/box/box.module.ts
- src/box/dailyTask/dailyTask.service.ts
- src/box/sessionStarter/sessionStarter.service.ts
- src/dailyTasks/dailyTasks.schema.ts
- src/dailyTasks/dailyTasks.service.ts
Added _/box/start_ POST endpoint to start testing session. Notice that only box admin can start a testing session.
- Added _/box/start_ POST endpoint to start testing session
- Added tests for the `SessionStarterService` class
- Added `createOne()` and `createMultiple()` methods to `DailyTaskService`
> Added /box/start POST endpoint to start testing session

- src/__tests__/player/customCharacter/CustomCharacterService/createOne.test.ts
- src/characterClass/files/jozsef.txt
- src/player/customCharacter/customCharacter.service.ts
Validate if CustomCharacter is already exists for _/customCharacter_ POST endpoint. Return with 409 error code if yes. Small code quality improvements.
- CustomCharacterService: rename model variable to customCharacterModel
- CustomCharacterService: validate if CustomCharacter is already exists. Return with 409 error code if yes.
- Move the CustomCharacter request validations to a separate method
> Fixed bug, where player can add multiple same type custom characters to own account

- src/clan/clan.schema.ts
- src/clan/dto/createClan.dto.ts
- src/clan/dto/updateClan.dto.ts
Added max length to clan name in create and update DTO's and clan schema
Updates to `Clan` schema:
* [`src/clan/clan.schema.ts`](diffhunk://#diff-2b0a6d9aa16122d4b8f08d8ea3430f94dce5476a904154c3f90f19b5127e0147L15-R15): Added `maxlength: 20` to the `name` property to enforce a maximum length constraint.
Updates to DTOs:
* [`src/clan/dto/createClan.dto.ts`](diffhunk://#diff-f81896d9b4df86ee462fa096af094058561efd1ecefe0fe8428f3ba55b8a3d4dR9): Imported `MaxLength` from `class-validator` and added `@MaxLength(20)` to the `name` property in `CreateClanDto`. [[1]](diffhunk://#diff-f81896d9b4df86ee462fa096af094058561efd1ecefe0fe8428f3ba55b8a3d4dR9) [[2]](diffhunk://#diff-f81896d9b4df86ee462fa096af094058561efd1ecefe0fe8428f3ba55b8a3d4dR22)
* …
> Fix: add maxlength validation for clan name in DTOs and schema

- src/__tests__/common/interceptor/response/SerializeInterceptor2/SerializeInterceptor2.test.ts
- src/common/decorator/response/UniformResponse.ts
- src/common/interceptor/response/SerializeInterceptor2.ts
- src/profile/profile.controller.ts
- src/profile/profile.service.ts
The bug with endpoints which exposed profile password is fixed. The problem was that the `@Serialize()` decorator does not work properly with the `@UniformResponse()` decorator or more precisely  with `FormatAPIResponseInterceptor` interceptor. 
In case when both of the decorators are in use the order in which they are applied matters, so as a solution I created a new interceptor for serialization: `SerializeInterceptor2`, which recognize `IServiceResponse` format tuples or objects and arrays returned by controller methods. And then this interceptor is added to the `@UniformResponse()` to the right order position. This interceptor should then be used everywhere where is the serialization is required and the `@UniformResponse()` is used.
- Added new `SerializeInterceptor2` interceptor for …
> Fixed endpoints exposing profile password

- src/clanShop/clanShop.controller.ts
- src/clanShop/clanShop.module.ts
This PR adds a new controller for the clan shop feature in the api. The changes include the addition of the `ClanShopController` and an endpoint to get the shop items.
- Added the `ClanShopController`
- Added `GET /clan-shop/items` endpoint to get the shop items.
- Added the new controller to the `ClanShopModule`.
> Added endpoint for getting clan shop items

- src/__tests__/clan/data/clan/ClanBuilder.ts
- src/__tests__/player/PlayerService/getAll.test.ts
- src/__tests__/player/PlayerService/getPlayerById.test.ts
- src/__tests__/player/PlayerService/readOneWithCollections.test.ts
- src/clan/clan.schema.ts
- src/clan/dto/clan.dto.ts
- src/clan/role/ClanRole.schema.ts
- src/clan/role/dto/clanRole.dto.ts
- src/clan/role/enum/clanBasicRight.enum.ts
- src/clan/role/enum/clanRoleType.enum.ts
- src/clan/role/initializationClanRoles.ts
`roles` field is added to clan data containing clan roles data, as well as required enums and clan initialization roles (leader, elder and member).
- Added schema for clan role
- Added enums `ClanBasicRight` and `ClanRoleType`
- Added `roles` field to clan schema and DTO
- Fixed failing tests after adding the `roles` field to clan schema
> Added roles field to clan data

- src/box/sessionStarter/sessionStarter.service.ts
- src/clan/role/ClanRole.schema.ts
- src/clan/role/initializationClanRoles.ts
- src/dailyTasks/dailyTasks.schema.ts
Set the default value of `player_id` field in daily tasks to `null`, so that it could be easier to debug on the game side
- Set the `player_id` field default value to `null`
- Set `player_id` to null for all daily tasks on server, which was not set
- Fix found bugs with `ClanRole` class
> Set player_id field to null by default for daily tasks

- src/__tests__/auth/AuthService/signIn.test.ts
- src/__tests__/auth/box/BoxAuthService/signIn.test.ts
- src/__tests__/auth/modules/authCommonModule.ts
- src/__tests__/box/BoxCreator/createBox.test.ts
- src/__tests__/clan/ClanService/createOne.test.ts
- src/__tests__/clan/ClanService/readOneById.test.ts
- src/__tests__/clan/data/clan/ClanBuilder.ts
- src/__tests__/clan/join/JoinService/handleJoinRequest.test.ts
- src/__tests__/player/data/player/playerBuilder.ts
- src/__tests__/test_utils/const/loggedUser.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/box/BoxAuthService.ts
- src/authorization/rule/playerRules.ts
- src/clan/clan.service.ts
- src/clan/join/join.service.ts
- src/player/dto/player.dto.ts
- src/player/schemas/player.schema.ts
Added clan member role information to the `Player` data as `clanRole_id`, so that it is possible to determine what role player has in his / her clan by the role _id. Since the player is not necessary gonna be in any clan, the default value of the `clanRole_id` is set to null.
Notice that the clan creator automatically will get the _Leader_ role in the created clan and that any new clan joined player will get the `Member` role.
Notice that it is not possible to set the `clanRole_id` field by making a request straight to the _/player_ POST or PUT endpoints and can be done only via a separate endpoints. 
- Added `clanRole_id` to player DTO and DB schema
- Added `clanRole_id` to player testing data builders
- Fixed bugs raised after the `roles` field was added to clan data with signing in …
> Added clan role information to player data

- src/__tests__/clan/role/ClanRoleService/ClanRoleService.deleteOneById.test.ts
- src/clan/role/clanRole.controller.ts
- src/clan/role/clanRole.service.ts
Create the endpoint for deleting a clan role by its _id field.
Add tests that cover the delete clan role functionality.
- clanRole.controller: add delete Create the endpoint for deleting a clan role by its _id field
- clanRolse.servcie: add deleteOneById, validateClanRoleDeleteRequest and validateClanRoleType methods
- Add ClanRoleService.deleteOneById() test suite
> Added endpoint to delete named role from clan

- src/__tests__/clan/data/clanBuilderFactory.ts
- src/__tests__/clan/data/role/UpdateClanRoleDtoBuilder.ts
- src/__tests__/clan/role/ClanRoleService/ClanRoleService.deleteOneById.test.ts
- src/__tests__/clan/role/ClanRoleService/ClanRoleService.updateOneById.test.ts
- src/clan/role/clanRole.controller.ts
- src/clan/role/clanRole.service.ts
- src/clan/role/dto/updateClanRole.dto.ts
Added endpoint to update a named role _/clan/role_ PUT. Notice that default and personal clan roles are not allowed to be changed via this endpoint.
- Added _/clan/role_ PUT
- Refactored `ClanRoleService`
- Added tests for the `ClanRoleService`
> Added endpoint for updating clan role

- src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
- src/__tests__/onlinePlayers/modules/onlinePlayers.module.ts
- src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
- src/onlinePlayers/onlinePlayers.controller.ts
- src/onlinePlayers/onlinePlayers.module.ts
- src/onlinePlayers/onlinePlayers.service.ts
This pull request makes a change to the data caching of online players. The cache now stores and returns objects containing player name and id instead of just id.
- Updated the `ping` method in `OnlinePlayersController` to return the result of `addPlayerOnline`, since the method can now throw.
- Added `PlayerModule` as an import in `OnlinePlayersModule` to enable the use of `PlayerService` within the `OnlinePlayersService`.
- Updated `addPlayerOnline` in `OnlinePlayersService` to fetch player details using `PlayerService` and store both the player ID and name in the cache.
- Modified `getAllOnlinePlayers` in `OnlinePlayersService` to return an array of JSON objects containing player IDs and names, instead of just IDs.
> The online players now returns an object containing name and id

- src/box/box.controller.ts
- src/box/dailyTask/dailyTask.controller.ts
- src/chat/chat.controller.ts
- src/clan/clan.controller.ts
- src/clanInventory/soulhome/soulhome.controller.ts
- src/dailyTasks/dailyTasks.controller.ts
- src/fleaMarket/fleaMarket.controller.ts
- src/leaderboard/leaderboard.controller.ts
- src/player/customCharacter/customCharacter.controller.ts
- src/player/player.controller.ts
- src/voting/dto/vote.dto.ts
- src/voting/dto/voting.dto.ts
- src/voting/voting.controller.ts
This pr refactors the use of `@Serialize` decorator in multiple controllers. All the endpoints that used the `Serialize` decorator are now replaced with `UniformResponse` decorator.
- All `@Serialize(someDto)` replaced with `@UniformResponse(someModel, someDto)`
- Added VoteDto to use in VotingDto
> Replace Serialize decorator with UniformResponse

- src/__tests__/clan/data/clanBuilderFactory.ts
- src/__tests__/clan/data/role/SetClanRoleBuilder.ts
- src/__tests__/clan/role/ClanRoleService/ClanRoleService.setRoleToPlayer.test.ts
- src/__tests__/clan/role/decorator/guard/HasClanRightsGuard/canActivate.test.ts
- src/__tests__/player/data/player/playerBuilder.ts
- src/clan/role/clanRole.controller.ts
- src/clan/role/clanRole.service.ts
- src/clan/role/decorator/guard/HasClanRights.ts
- src/clan/role/dto/setClanRole.dto.ts
- src/clan/role/payloads/SetClanRole.ts
- src/common/controller/APIError.ts
- src/common/exceptionFilter/APIErrorFilter.ts
Added _/clan/role/set_ PUT endpoint to set a default or named role to a specified player. Notice the limitations of this endpoint in the attached issue.
- Added _/clan/role/set_ PUT endpoint
- Added tests
- Fixed bug with `APIError` error filter by introducing a new wrapper class, which holds an array of `APIError` and behaves similarly to array
> Added /clan/role/set PUT endpoint for setting a role for a clan member

- src/clan/clan.controller.ts
OffsetPaginate validate if the response already contains the metaData and wont populate the paginationData into the response if the metaData is missing. UniformResponse populate the metaData, it need to be executed before than the OffsetPaginate.
- clan.controller:  put the UniformResponse attribute on top of the OffsetPaginate attribute in order to get populated the paginationData object in the response for the get clan api
> Fixed a bug where /clan GET endpoint does not return pagination data

- src/leaderboard/dto/leaderboardPlayer.dto.ts
- src/leaderboard/leaderboard.controller.ts
- src/leaderboard/leaderboard.service.ts
this PR enhances the player leaderboard data by adding the clan logo data to it and fixes the missing pagination data from response.
- New DTO for leaderboard players that extends the PlayerDto with added clanLogo prop.
- Replaced PlayerDto with LeaderboardPlayerDto in `@UniformResponse` decorator in player leaderboard endpoint.
- Added logic to `LeaderboardService` to fetch clan logos for players.
> Feature add clan logo to player leaderboard data

- src/common/interceptor/response/Send204OnEmptyRes.ts
- src/profile/profile.controller.ts
Fixed endpoints, which was returning 200 status code instead of 204. The errors was caused by `Send204OnEmptyResInterceptor` class did not await the incoming data.
- Fixed _/profile_ DELETE endpoint
- Fixed _/clan_ PUT endpoint
- Fixed _/clan_ DELETE endpoint
- Fixed _/item_ PUT endpoint
> Fixed wrong response types retunred from endpoints

- src/clanInventory/item/item.controller.ts
Added edit soul home permission validation for /item PUT endpoint, which updates `location` field of a specified item
- Added edit soul home permission validation for /item PUT
> Added edit soul home permission validation for /item PUT endpoint

- src/__tests__/common/decorator/validation/IsMongoIdOrNull/IsMongoIdOrNull.test.ts
- src/__tests__/player/PlayerService/createOne.test.ts
- src/__tests__/player/PlayerService/updateOneById.test.ts
- src/__tests__/player/data/player/createPlayerDtoBuilder.ts
- src/__tests__/player/data/player/playerBuilder.ts
- src/__tests__/player/data/player/playerDtoBuilder.ts
- src/__tests__/player/data/player/updatePlayerDtoBuilder.ts
- src/common/decorator/validation/IsMongoIdOrNull.decorator.ts
- src/player/dto/createPlayer.dto.ts
- src/player/dto/updatePlayer.dto.ts
Change validation of Player.battleCharacter_ids to also accept null as a value.
- Add @IsMongoIdOrNull() decorator
- Replace the battleCharacter_ids @IsMongoId() decorator with @IsMongoIdOrNull() in the createPlayer/updatePlayer DTOs
- Made all player (DTO and schema) battleCharacter_ids nullable
- Extends tests to cover the changes
> Change player battle characters storing mechanism   517

- src/__tests__/common/service/redis/mocks/RedisServiceInMemory.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
- src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
- src/common/service/redis/IRedisService.ts
- src/common/service/redis/redis.service.ts
- src/onlinePlayers/dto/InformPlayerIsOnline.dto.ts
- src/onlinePlayers/dto/onlinePlayer.dto.ts
- src/onlinePlayers/enum/OnlinePlayerStatus.ts
- src/onlinePlayers/onlinePlayers.controller.ts
- src/onlinePlayers/onlinePlayers.service.ts
- src/onlinePlayers/payload/AddOnlinePlayer.ts
- src/onlinePlayers/payload/OnlinePlayer.ts
Online players now have a `status` field, which determines what player is doing or where he/she is in the game. The possible values of it are:
- UI (player just online somewhere in UI)
- BattleWait (player is waiting for a battle)
- Battle (player is playing the battle)
Notice that if the status value is not specified in the _/online-players/ping POST_, the UI value is set by default
- Added body with optional field `status` for _/online-players/ping POST_ endpoint
- Added `status` field in return of _online-players GET_ endpoint
- Refactored `RedisService` and the use of it in the `onlinePlayers` module
> Added "status" field for online players

- src/__tests__/onlinePlayers/OnlinePlayersService/getAllOnlinePlayers.test.ts
- src/onlinePlayers/dto/OnlinePlayerSearchQuery.dto.ts
- src/onlinePlayers/onlinePlayers.controller.ts
- src/onlinePlayers/onlinePlayers.service.ts
Now it is possible to filter online players by `status` field. It is possible to filter them by one or by multiple values. For example:
`?search=status="UI" //only players with status UI` 
or 
`?search=status="UI";AND;status="Battle" //only players with status UI or Battle`
- Added search query to _/online-players GET_ endpoint
> Added filtering for /online-players GET enpoint by `status` field

- src/leaderboard/leaderboard.service.ts
It is a temporary solution, which should resolve the problem that some of the player or clan data can be updated in the DB, but not in the leaderboard. With shorter TTL, it should be ok for now. Later possibly some other mechanism will be required. See the linked issue conversation
- Change TTL for leaderboards to 3 hours
> Changed time to live for leaderboards to 3h

- src/__tests__/common/service/redis/mocks/RedisServiceInMemory.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/addPlayerOnline.test.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/getOnlinePlayerById.test.ts
- src/__tests__/onlinePlayers/OnlinePlayersService/getOnlinePlayers.test.ts
- src/__tests__/onlinePlayers/battleQueue/BattleQueueService/getPlayerQueueNumber.test.ts
- src/__tests__/onlinePlayers/battleQueue/BattleQueueService/sortPlayersByQueueNumber.test.ts
- src/__tests__/onlinePlayers/data/onlinePlayers/AddOnlinePlayerBuilder.ts
- src/__tests__/onlinePlayers/data/onlinePlayers/OnlinePlayerBuilder.ts
- src/__tests__/onlinePlayers/data/onlinePlayersBuilderFactory.ts
- src/__tests__/onlinePlayers/modules/battleQueue.module.ts
- src/__tests__/onlinePlayers/modules/onlinePlayersCommon.module.ts
- src/common/service/redis/cacheKeys.enum.ts
- src/leaderboard/leaderboard.controller.ts
- src/onlinePlayers/battleQueue/battleQueue.controller.ts
- src/onlinePlayers/battleQueue/battleQueue.service.ts
- src/onlinePlayers/dto/onlinePlayer.dto.ts
- src/onlinePlayers/onlinePlayers.controller.ts
- src/onlinePlayers/onlinePlayers.module.ts
- src/onlinePlayers/onlinePlayers.service.ts
- src/onlinePlayers/payload/OnlinePlayer.ts
- src/onlinePlayers/payload/additionalTypes/BattleWaitStatus.ts
Added  _/online-players/battleQueue GET_ endpoint, which returns online players with status _BattleWait_ = players waiting to join the battle, in the right order number, where first are the players, being first in the queue and in the end the last.
- Added  _/online-players/battleQueue GET_ endpoint
- Moved next queue number from API code to Redis, so that there are no problems with syncing this number when API might be restarted, bit Redis not.
> Added /online-players/battleQueue GET endpoint to retrieve online players waiting in battle queue

- src/__tests__/box/accountClaimer/TesterAccountService/createTester.test.ts
- src/__tests__/fleaMarket/stall/StallService/buyStallSlot.test.ts
- src/auth/auth.controller.ts
- src/auth/box/BoxAuthService.ts
- src/box/accountClaimer/accountClaimer.service.ts
- src/box/accountClaimer/testerAccount.service.ts
- src/box/auth/boxAuth.guard.ts
- src/clan/clan.schema.ts
- src/clan/defaultValues/stall.ts
- src/fleaMarket/stall/dto/buyStallSlot.dto.ts
- src/fleaMarket/stall/stall.controller.ts
- src/fleaMarket/stall/stall.service.ts
Added endpoint to buy more stall slots.
- Added `POST /buy-slot` endpoint
- Added service method for buying the logic
- Added tests for the service method
- Added get default values function for stalls
- Removed the groupAdmin requirements from auth guard to make it possible for all test players to use the endpoints.
> Add buy extra stall slot endpoint

- src/__tests__/fleaMarket/FleaMarketService/moveFleaMarketItemToStock.test.ts
- src/__tests__/fleaMarket/FleaMarketService/moveFleaMarketItemToStockTransaction.test.ts
- src/__tests__/fleaMarket/modules/fleaMarketModule.ts
- src/fleaMarket/errors/itemBooked.error.ts
- src/fleaMarket/fleaMarket.controller.ts
- src/fleaMarket/fleaMarket.service.ts
Add new endpoint to move items from fleamarket to stock.
- Add `POST /move-to-stock/:_id` endpoint
- Add service methods to handle the item moving
- Add tests for the service methods
> feat: add tests for moving flea market items to stock

- src/clanShop/clanShop.controller.ts
Possible `clanShop/buy` endpoint errors were missing from the response due to missing return statement in the method call.
- Added return statement to return possible errors from buyItem call
> Buy item endpoint not adding errors to responses.

- src/box/box.module.ts
- src/box/box.service.ts
- src/box/boxCreator.ts
- src/box/schemas/ClanToCreate.v2.schema.ts
- src/box/schemas/box.v2.schema.ts
Changed the box schema to use Types.ObjectId instead of plain ObjectId like documentation suggests. Added the `@Schema` decorator to clanToCreate schema to make the default value work and removed the unnecessary _id from that schema.
Register the new schema in box module
Inject the new model in box.service
> Enhance and register the v2 box schema

- src/common/plugin/addBoxIdToSchema.plugin.ts
The plugin was adding the box_id to all schemas which was unnecessary. The teacher profile and box do not need that and neither do the subschemas like clansToCreate.
> addBoxIdToSchema changes

- src/box/auth/boxAuth.guard.ts
- src/box/box-user.factory.ts
- src/box/box.module.ts
- src/teacher/teacher.service.ts
* Updated the `TeacherService` to include a `groupAdmin: true` property in the JWT access token when creating or logging in a teacher, ensuring downstream services can identify group admins. [[1]](diffhunk://#diff-7bea637ef65d2633fe76edc0e14ae20cedf306b37cb1b189f7c8ec01d28305ccR43) [[2]](diffhunk://#diff-7bea637ef65d2633fe76edc0e14ae20cedf306b37cb1b189f7c8ec01d28305ccR79)
* Modified the `BoxAuthGuard` to allow requests with a valid `profile_id` and `groupAdmin` flag to pass authentication, streamlining access for group admins.
> Added teacher profile auth logic
