src/app.module.ts, src/authorization/caslAbility.factory.ts, src/authorization/rule/joinRequestRules.ts, src/clan/clan.controller.ts, src/clan/clan.schema.ts, src/clan/dto/clan.dto.ts, src/clan/dto/createClan.dto.ts, src/clan/dto/updateClan.dto.ts, src/clan/join/dto/join.dto.ts, src/clan/join/dto/joinRequest.dto.ts, src/clan/join/dto/joinResult.dto.ts, src/clan/join/join.controller.ts, src/clan/join/join.module.ts, src/clan/join/join.schema.ts, src/clan/join/join.service.ts, src/common/enum/modelName.enum.ts
Endpoint for joining clans (`clan/join`) where you send a `clan_id , player_id` and an optional `join_message`.
added a boolean to clan `isOpen` which decides whether a clan is open or not.
=> Joining a clan

src/common/base/decorator/AddBasicService.decorator.ts, src/common/interface/IHookImplementer.ts
added ```PostReadOneHook``` and ```PostReadAllHook``` into basicservice
=> added new Hook functions

src/app.module.ts, src/authorization/caslAbility.factory.ts, src/authorization/rule/clanVoteRules.ts, src/authorization/rule/shopRules.ts, src/clan/defaultValues/items.ts, src/clan/join/join.service.ts, src/common/base/decorator/AddBasicService.decorator.ts, src/common/enum/modelName.enum.ts, src/common/function/timeUtils.ts, src/common/interface/IHookImplementer.ts, src/item/item.schema.ts, src/item/item.service.ts, src/shop/clanVote/clanVote.controller.ts, src/shop/clanVote/clanVote.module.ts, src/shop/clanVote/clanVote.schema.ts, src/shop/clanVote/clanVote.service.ts, src/shop/clanVote/dto/clanVote.dto.ts, src/shop/clanVote/dto/createClanVote.dto.ts, src/shop/clanVote/dto/updateClanVote.dto.ts, src/shop/itemShop/dto/createItemshop.dto.ts, src/shop/itemShop/dto/createShopItem.dto.ts, src/shop/itemShop/dto/itemshop.dto.ts, src/shop/itemShop/dto/shopItem.dto.ts, src/shop/itemShop/itemShop.controller.ts, src/shop/itemShop/itemShop.module.ts, src/shop/itemShop/itemShop.schema.ts, src/shop/itemShop/itemShop.service.ts, src/shop/itemShop/shopItems.json, src/stock/stock.schema.ts
Also added some hooks into basicservice
=> Add shop with voting functionality

src/Room/room.schema.ts, src/clan/clan.module.ts, src/clan/clan.service.ts, src/clan/join/join.module.ts, src/clan/join/join.service.ts, src/shop/clanVote/clanVote.service.ts, src/soulhome/soulhome.schema.ts
soulhome and roomcreations by default into join and clan
=> Add extra checks for clanvote POST and add

swagger/swagger.json
=> add swagger for /room

swagger/swagger.json
=> add swagger description for /soulhome

swagger/swagger.json
1. Write swagger for /stock, /stock/:_id and /stock/steal
2. Write swagger for /gameData/battle. 
This /gameData endpoint is a prototype of how the game side data required on the API side can be accessed.
Closes #79
=> Write swagger for /stock

swagger/swagger.json
=> add swagger for /item

src/player/test.txt
The test.txt has been created on this branch and this is the pull request for that.
=> test.txt added to src/player

src/authorization/caslAbility.factory.ts, src/characterClass/characterClass.controller.ts, src/common/base/decorator/AddType.decorator.ts, src/common/controller/formatResponse.ts, src/common/service/basicService/BasicService.ts, src/common/service/basicService/IService.ts, src/common/service/basicService/SEReason.ts, src/common/service/basicService/ServiceError.ts
=> add response formatting function

src/common/base/abstract/basicAndConditionServiceDummy.abstract.ts, src/common/base/abstract/basicServiceDummy.abstract.ts, src/common/base/abstract/conditionServiceDummy.abstract.ts, src/common/base/decorator/AddConditionService.decorator.ts, src/common/base/decorator/BasicDELETE.decorator.ts, src/common/base/decorator/BasicGET.decorator.ts, src/common/base/decorator/BasicPOST.decorator.ts, src/common/base/decorator/BasicPUT.decorator.ts, src/common/base/decorator/ThrowNotImplementedMethod.decorator.ts, src/common/decorator/response/CatchCreateUpdateErrors.ts, src/common/decorator/response/ThrowResponseErrorIfFound.ts, src/common/decorator/response/responseType.ts, src/common/enum/apiObjectName.enum.ts, src/common/enum/discriminator.enum.ts, src/common/enum/stockType.enum.ts, src/common/interceptor/request/addMetaDataQuery.interceptor.ts, src/common/interceptor/request/cursorPagination.interceptor.ts, src/util/parser/IFieldParser.ts, src/util/parser/fieldParser.ts
=> mark files as deprecated

src/characterClass/characterClass.controller.ts, src/common/decorator/param/LoggedUser.decorator.ts
1. Add the decorator
2. Add examples of its use
=> add LoggedUser decorator for controller methods PR

src/Room/room.module.ts, src/Room/room.service.ts, src/item/item.controller.ts, src/item/item.service.ts
1. Update deleteOneById() to also remove associated items in RoomService
2. Add method for removing all Rooms with associated SoulHome
3. Remove some redundant code.
Closes #118
=> add room deletion methods PR

src/item/item.controller.ts, src/item/item.service.ts
1. Add deleteAllStockItems() and deleteAllRoomItems()
2. Update JSDocs for ItemService
=> Add item deletion methods PR

src/item/item.controller.ts, src/item/item.service.ts, src/stock/stock.module.ts, src/stock/stock.service.ts
Now the deleteOneById() also removes all items of the stock
=> update stock deletion method PR

src/authorization/caslAbility.factory.ts, src/authorization/rule/roomRules.ts, src/authorization/rule/soulHomeRules.ts, src/clan/clan.service.ts, src/clan/defaultValues/soulHome.ts, src/soulhome/dto/createSoulHome.dto.ts, src/soulhome/dto/soulhome.dto.ts, src/soulhome/dto/updateSoulHome.dto.ts, src/soulhome/soulhome.controller.ts, src/soulhome/soulhome.module.ts, src/soulhome/soulhome.schema.ts, src/soulhome/soulhome.service.ts, src/soulhome/utils/soulHomeHelper.service.ts
1. Change old logic of SoulHome to meet new requirements
2. Remove SoulHome module usages from ClanModule temporary
=> Add SoulHome basic logic PR

src/clan/test.txt
=> Add test.txt file

src/clan/clan.schema.ts, src/clan/dto/clan.dto.ts, src/clan/dto/createClan.dto.ts, src/clan/dto/updateClan.dto.ts, src/clan/enum/ageRange.enum.ts, src/clan/enum/goal.enum.ts, src/common/enum/language.enum.ts, swagger/swagger.json
1. Add ageRange, goals, phrase, language fields to Clan DTOs and schema
2. Update swagger accordingly
3. Remove `gameCoins` field from Clan creation and updating DTOs, since player should not be able to update them
=> add new required fields to Clan model

src/app.module.ts, src/common/service/envHandler/envHandler.ts, src/common/service/envHandler/envVars.ts, src/gameAnalytics/logFile.service.ts, src/main.ts
1. Add `envVars` record containing all env vars
2. Add class with env vars validation method
3. Add validation of env vars on API start
=> add env handler class

src/gameData/gameData.service.ts, src/playerTasks/playerTasks.service.ts
Added a call to task service with win_battle type after validating that user is in the winning team.
=> Add call to taskService to track won battles

src/test/clan_module/data/clan/ClanBuilder.ts, src/test/clan_module/data/factory.ts, src/test/common/service/counter/Counter/Counter.decrease.test.ts, src/test/common/service/counter/Counter/Counter.decreaseById.test.ts, src/test/common/service/counter/Counter/Counter.decreaseByIdOnOne.test.ts, src/test/common/service/counter/Counter/Counter.decreaseOnOne.test.ts, src/test/common/service/counter/Counter/Counter.increase.test.ts, src/test/common/service/counter/Counter/Counter.increaseById.test.ts, src/test/common/service/counter/Counter/Counter.increaseByIdOnOne.test.ts, src/test/common/service/counter/Counter/Counter.increaseOnOne.test.ts, src/test/common/service/envHandler/EnvHandler/EnvHandler.validateAllEnvFound.test.ts
=> add tests for EnvHandler class

src/test/clan_module/data/clan/ClanBuilder.ts, src/test/clan_module/data/factory.ts, src/test/common/service/counter/Counter/Counter.decrease.test.ts, src/test/common/service/counter/Counter/Counter.decreaseById.test.ts, src/test/common/service/counter/Counter/Counter.decreaseByIdOnOne.test.ts, src/test/common/service/counter/Counter/Counter.decreaseOnOne.test.ts, src/test/common/service/counter/Counter/Counter.increase.test.ts, src/test/common/service/counter/Counter/Counter.increaseById.test.ts, src/test/common/service/counter/Counter/Counter.increaseByIdOnOne.test.ts, src/test/common/service/counter/Counter/Counter.increaseOnOne.test.ts
=> add tests for counter class

src/test/common/service/notificator/MQTTConnector/MQTTConnector.connect.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.disconnect.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.getInstance.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.publish.test.ts, src/test/common/service/notificator/NotificationSender/NotificationSender.buildNotification.test.ts
1. add tests for all NotificationSender class methods 
=> add tests for NotificationSender class 

src/test/common/service/notificator/MQTTConnector/MQTTConnector.connect.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.disconnect.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.getInstance.test.ts, src/test/common/service/notificator/MQTTConnector/MQTTConnector.publish.test.ts
1. tests for all MQTTConnector class methods
=> add tests for MQTTConnector class

src/common/interceptor/request/addSearchQuery.interceptor.ts, src/common/interceptor/request/addSortQuery.interceptor.ts, src/test/common/interceptor/request/AddSearchQueryInterceptor/AddSearchQueryInterceptor.test.ts, src/test/common/interceptor/request/AddSearchQueryInterceptor/AddSortQueryInterceptor.test.ts, src/test/test_utils/data/BodyBuilder.ts, src/test/test_utils/data/CallHandlerBuilder.ts, src/test/test_utils/data/ExecutionContextBuilder.ts, src/test/test_utils/data/RequestBuilder.ts, src/test/test_utils/data/TestUtilsDataFactory.ts
1. Add tests for AddSortQueryInterceptor class intercept method
=> add test for AddSortQueryInterceptor class

src/common/interceptor/request/addSearchQuery.interceptor.ts, src/test/common/interceptor/request/AddSearchQueryInterceptor/AddSearchQueryInterceptor.test.ts, src/test/test_utils/data/BodyBuilder.ts, src/test/test_utils/data/CallHandlerBuilder.ts, src/test/test_utils/data/ExecutionContextBuilder.ts, src/test/test_utils/data/RequestBuilder.ts, src/test/test_utils/data/TestUtilsDataFactory.ts
1. helper data builders for express and NestJS objects
2. tests for AddSearchQueryInterceptor intercept
=> add tests for AddSearchQueryInterceptor class

src/test/common/function/addUniqueArrayElements/addUniqueArrayElements.test.ts, src/test/common/function/deleteArrayElements/deleteArrayElements.test.ts, src/test/common/function/deleteNotUniqueArrayElements/deleteNotUniqueArrayElements.test.ts, src/test/common/function/timeUtils/timeUtils.test.ts
1. tests for all functions in the common/function package
=> add tests for common/function package functions

src/common/interceptor/response/Send204OnEmptyRes.ts, src/common/interceptor/response/Serialize.ts, src/test/common/interceptor/response/Send204OnEmptyResInterceptor/Send204OnEmptyResInterceptor.test.ts, src/test/common/interceptor/response/SerializeInterceptor/SerializeInterceptor.test.ts
1. tests for SerializeInterceptor intercept()
=> add tests for SerializeInterceptor class

src/common/interceptor/response/Send204OnEmptyRes.ts, src/test/common/interceptor/response/Send204OnEmptyResInterceptor/Send204OnEmptyResInterceptor.test.ts
1. tests for Send204OnEmptyResInterceptor intercept()
=> add tests for Send204OnEmptyResInterceptor class

src/test/common/exceptionFilter/ValidationExceptionFilter/ValidationExceptionFilter.catch.test.ts, src/test/common/exceptionFilter/ValidationExceptionFilter/ValidationExceptionFilter.validationToAPIErrors.test.ts, src/test/test_utils/data/BadRequestExceptionBuilder.ts, src/test/test_utils/data/TestUtilsDataFactory.ts, src/test/test_utils/data/ValidationErrorBuilder.ts
1. Tests for ValidationExceptionFilter.catch()
2. Tests for ValidationExceptionFilter.validationToAPIErrors()
3. BadRequestExceptionBuilder test data builder
4. ValidationErrorBuilder test data builder
=> add tests for ValidationExceptionFilter class

src/common/decorator/validation/isEntityExists.ts, src/test/common/decorator/validation/isEntityExists/isEntityExists.defaultMessage.test.ts, src/test/common/decorator/validation/isEntityExists/isEntityExists.validate.test.ts, src/test/test_utils/data/TestUtilsDataFactory.ts
1. tests for isEntityExists class methods
2. JSDocs for isEntityExists class
=> add tests for isEntityExists class

src/clan/clan.module.ts, src/clanInventory/item/itemHelper.service.ts, src/clanInventory/room/room.service.ts, src/clanInventory/stock/stock.service.ts, src/gameData/gameData.service.ts, src/itemMover/itemMover.service.ts, src/rewarder/playerRewarder/playerRewarder.service.ts, src/rewarder/playerRewarder/points.ts
=> remove forwardRefs

src/characterClass/MikaR.txt
1. Loin ohjeiden mukaisen txt tiedoston.
=> Tehtävän annon mukainen tiedosto

src/test/common/controller/APIError/APIError.test.ts, src/test/common/controller/APIError/convertToAPIError.test.ts, src/test/common/controller/APIError/isAPIError.test.ts, src/test/common/controller/formatResponse.test.ts
1. Tests for common controller folder files
=> Add tests for common controller folder

src/playerTasks/playerTasks.service.ts
1. Fix the bug
2. A small imports refactor in `PlayerTasksService`
=> Fix bug with /playerTasks not returning tasks

src/leaderboard/leaderboard.controller.ts, swagger/swagger.json
=> Make /leaderboard public

src/characterClass/files/alexei.txt
1. A txt file for testing that i know team Git flow and have all right in the repo
=> add alexei.txt file

src/clanInventory/clanInventory.module.ts, src/test/clan/data/clan/ClanBuilder.ts, src/test/clan/data/clan/CreateClanDtoBuilder.ts, src/test/clan/data/clan/UpdateClanDtoBuilder.ts, src/test/clan/data/clan/join/JoinRequestDtoBuilder.ts, src/test/clan/data/clan/join/RemovePlayerDtoBuilder.ts, src/test/clan/data/clanBuilderFactory.ts, src/test/clan/modules/clan.module.ts, src/test/clan/modules/clanCommon.ts, src/test/player/PlayerService/createOne.test.ts, src/test/player/PlayerService/deleteByCondition.test.ts, src/test/player/PlayerService/deleteOneById.test.ts, src/test/player/PlayerService/getAll.test.ts, src/test/player/PlayerService/getPlayerById.test.ts, src/test/player/PlayerService/readAll.test.ts, src/test/player/PlayerService/readOneById.test.ts, src/test/player/PlayerService/readOneWithAllCollections.test.ts, src/test/player/PlayerService/readOneWithCollections.test.ts, src/test/player/PlayerService/updateOneById.test.ts, src/test/player/PlayerService/updatePlayerById.test.ts, src/test/player/data/player/gameStatisticsBuilder.ts, src/test/player/data/player/playerBuilder.ts, src/test/player/data/player/updatePlayerDtoBuilder.ts, src/test/player/data/playerBuilderFactory.ts, src/test/player/modules/playerCommon.module.ts, src/test/test_utils/util/removeDBDefaultFields.ts
1. Add tests for all PlayerService class methods
=> add tests for PlayerService class

src/fleaMarket/fleaMarket.service.ts, src/voting/dto/addVote.dto.ts, src/voting/dto/createVoting.dto.ts, src/voting/dto/voting.dto.ts, src/voting/error/addVote.error.ts, src/voting/error/alreadyVoted.error.ts, src/voting/error/noPermission.error.ts, src/voting/schemas/vote.schema.ts, src/voting/schemas/voting.schema.ts, src/voting/type/notifierPayload.type.ts, src/voting/type/startItemVoting.type.ts, src/voting/voting.controller.ts, src/voting/voting.notifier.ts, src/voting/voting.service.ts
This PR includes the following changes
1. Added /voting PUT endpoint and methods to validate and the new vote to the voting document.
2. Bugfix for the voting notifier. The old payload did not match the one defined in the drawio diagram. So I changed the parameters passed by some methods and added the virtual field for flea market item to the voting schema so the notifier receives all the information it needs. I also added the payload builder helper method to the notifier.
=> Feature/add /voting endpoint 200

swagger/swagger.json
1. Add swagger description for /clan/items
=> add swagger description for /clan/items

src/clan/dto/createClan.dto.ts, src/clan/dto/updateClan.dto.ts, src/test/clan/data/clan/ClanBuilder.ts, src/test/clan/data/clan/CreateClanDtoBuilder.ts, src/test/clan/data/clan/UpdateClanDtoBuilder.ts, src/test/clan/data/clan/join/JoinRequestDtoBuilder.ts, src/test/clan/data/clan/join/RemovePlayerDtoBuilder.ts
1. Fix test data builders to include new `clanLogo` field
=> fix clan module tests

src/__tests__/chat/chatService/createMessage.test.ts, src/__tests__/clan/join/JoinService/handleJoinRequest.test.ts, src/__tests__/customCharacter/CustomCharacterService/createOne.test.ts, src/__tests__/customCharacter/CustomCharacterService/deleteMany.test.ts, src/__tests__/customCharacter/CustomCharacterService/readMany.test.ts, src/__tests__/customCharacter/CustomCharacterService/readOneById.test.ts, src/__tests__/customCharacter/CustomCharacterService/updateOneById.test.ts, src/__tests__/customCharacter/data/customCharacter/CreateCustomCharacterDtoBuilder.ts, src/__tests__/customCharacter/data/customCharacter/CustomCharacterBuilder.ts, src/__tests__/customCharacter/data/customCharacter/UpdateCustomCharacterDtoBuilder.ts, src/__tests__/customCharacter/data/customCharacterBuilderFactory.ts, src/__tests__/customCharacter/modules/customCharacter.module.ts, src/__tests__/customCharacter/modules/customCharacterCommon.ts, src/__tests__/player/PlayerService/updateOneById.test.ts, src/common/service/basicService/ServiceError.ts, src/customCharacter/const/CharacterBaseStats.ts, src/customCharacter/customCharacter.controller.ts, src/customCharacter/customCharacter.module.ts, src/customCharacter/customCharacter.schema.ts, src/customCharacter/customCharacter.service.ts, src/customCharacter/dto/createCustomCharacter.dto.ts, src/customCharacter/dto/customCharacter.dto.ts, src/customCharacter/dto/updateCustomCharacter.dto.ts, src/customCharacter/enum/characterId.enum.ts, src/player/player.service.ts
1. Change the `CustomCharacter` schema to more appropriate
2. Add tests for `CustomCharacterService`
3. Change `CustomCharacterSerice` to use the newer BasicService for all DB calls
4. Change `CustomCharacterController` to use new methods of the `CustomCharacterSerice`
Closes #382 
=> change CustomCharacter to use BasicService

src/__tests__/customCharacter/CustomCharacterService/readOne.test.ts, src/__tests__/customCharacter/CustomCharacterService/updateOneByCondition.test.ts, src/authorization/rule/customCharacterRules.ts, src/customCharacter/customCharacter.controller.ts, src/customCharacter/customCharacter.service.ts
1. Add functionality to allowing manipulate (CRU) only own customer characters
2. Add helper methods and tests for them to `CustomCharacterService`
=> Add functionality to allowing manipulate only own customer characters

src/__tests__/player/customCharacter/decorator/validation/IsCustomCharacterExists/IsCustomCharacterExists.test.ts
1. add tests for @IsCustomCharacterExists() decorator
=> add tests for @IsCustomCharacterExists()

src/__tests__/clanInventory/data/item/updateItemDtoBuilder.ts, src/__tests__/clanInventory/item/ItemService/updateOneById.test.ts, src/authorization/rule/itemRules.ts, src/clanInventory/item/dto/createItem.dto.ts, src/clanInventory/item/dto/updateItem.dto.ts, src/clanInventory/item/item.controller.ts
1. Remove all fields except for `_id` and `location` from item update DTO
2. Fix failed tests after the DTO change
3. add /item PUT
=> Add item PUT endpoint

src/__tests__/auth/AuthService/signIn.test.ts, src/__tests__/auth/AuthService/verifyToken.test.ts, src/__tests__/auth/decorator/AuthGuard/canActivate.test.ts, src/__tests__/auth/decorator/ThrowAuthErrorIfFound.test.ts, src/__tests__/auth/modules/auth.module.ts, src/__tests__/auth/modules/authCommonModule.ts, src/auth/auth.service.ts
1. Add tests for `AuthService`
2. Add tests for auth module decorators
=> Add tests for auth module

.gitignore, package.json, sonar_docker-compose.yml, src/__tests__/itemMover/ItemMoverService/moveItem.test.ts, src/__tests__/itemMover/ItemMoverService/moveItems.test.ts, src/__tests__/itemMover/ItemMoverService/stealItems.test.ts, src/__tests__/itemMover/modules/itemMover.module.ts, src/__tests__/itemMover/modules/itemMoverCommon.module.ts, src/itemMover/itemMover.service.ts
1. Add tests for `ItemMoverService`
2. Add testing setup for itemMover module
=> add tests for item mover module

src/player/customCharacter/const/CharacterBaseStats.ts, src/player/customCharacter/enum/characterId.enum.ts
The types 102 "Bodybuilder" and 103 "Conman" of custom was added to the API and custom characters with those types can be created.
- Added 102 "Bodybuilder" and 103 "Conman" custom character types to be accepted on validation
- Added default characteristics for 102 and 103 custom characters
=> Add 102 and 203 custom character types

src/characterClass/files/jozsef.txt
Created jozsef.txt file
Add ..\src\characterClass\files folder
Add ..\files\jozsef.txt file
Add  "Hello world" to the file
=> Add new txt files with my own name.

package-lock.json, package.json, src/__tests__/box/BoxScheduler/resetTestingSessions.test.ts, src/__tests__/box/BoxService/resetTestingSessions.test.ts, src/__tests__/box/modules/box.module.ts, src/__tests__/box/modules/boxCommon.ts, src/app.module.ts, src/box/box.module.ts, src/box/box.scheduler.ts, src/box/box.service.ts
Added a cron job to delete expired testing sessions.
- Added nestjs schedule package to handle the cron jobs.
- Added cron job and method to box service to delete the ended sessions.
- Added unit tests for the new method
=> Added cron job for test sessions automating deletion

src/__tests__/player/modules/playerCommon.module.ts, src/player/dto/player.dto.ts, src/player/dto/task.dto.ts, src/player/player.controller.ts, src/player/player.schema.ts, src/player/player.service.ts
This pull request includes changes to integrate daily task info into the `GET /player/:id` endpoint response. The most important changes are updating the `PlayerDto` to include daily tasks, and modifying the `PlayerController` to add the task data to the response.
* [`src/__tests__/player/modules/playerCommon.module.ts`](diffhunk://#diff-ce6e36069dc660b6bfe14c8686e7ff682519d0406ed66696767ffb11efb221f8R17): Added `DailyTaskSchema` to the imports and updated the `PlayerCommonModule` to include the `DailyTaskSchema` in the model definitions. [[1]](diffhunk://#diff-ce6e36069dc660b6bfe14c8686e7ff682519d0406ed66696767ffb11efb221f8R17) [[2]](diffhunk://#diff-ce6e36069dc660b6bfe14c8686e7ff682519d0406ed66696767ffb11efb221f8L33-R35)
* [`src/player/dto/player.dto.ts`](diffhunk://#diff-9815ab64465aba7 …
=> Refactor GET /player/:id endpoint so it has daily task data in response.

src/__tests__/clan/data/clan/ClanBuilder.ts, src/__tests__/player/data/message/MessageBuilder.ts, src/__tests__/player/data/playerBuilderFactory.ts, src/__tests__/rewarder/ClanRewarder/rewardClanForPlayerTask.test.ts, src/__tests__/rewarder/PlayerRewarder/rewardForPlayerEvent.test.ts, src/__tests__/rewarder/PlayerRewarder/rewardForPlayerTask.test.ts, src/__tests__/rewarder/modules/clanRewarder.module.ts, src/__tests__/rewarder/modules/rewarderCommon.ts, src/rewarder/clanRewarder/clanRewarder.service.ts, src/rewarder/playerRewarder/playerRewarder.service.ts
Added unit tests for all service level classes in the rewarder module
- Added tests for `ClanRewarder`
- Added tests for `PlayerRewarder`
- Added new testing data builder for `Message` schema from _player_ module
- Added `setPoints()` method to `ClanBuilder`
- Improved JSDocs
=> Added unit tests for rewarder module

src/__tests__/clan/ClanHelperService/createDefaultSoulHome.test.ts, src/__tests__/clan/utils/defaultValues/getRoomDefaultItems.test.ts, src/__tests__/clanInventory/data/item/ItemBuilder.ts, src/__tests__/clanInventory/data/item/createItemDtoBuilder.ts, src/__tests__/clanInventory/item/ItemService/readMany.test.ts, src/__tests__/clanInventory/item/ItemService/updateMany.test.ts, src/__tests__/itemMover/ItemMoverService/moveItem.test.ts, src/__tests__/itemMover/ItemMoverService/moveItems.test.ts, src/__tests__/itemMover/ItemMoverService/stealItems.test.ts, src/clan/utils/defaultValues/items.ts, src/clanInventory/item/const/itemProperties.ts, src/clanInventory/item/dto/createItem.dto.ts, src/clanInventory/item/dto/item.dto.ts, src/clanInventory/item/enum/itemName.enum.ts, src/clanInventory/item/enum/material.enum.ts, src/clanInventory/item/enum/rarity.enum.ts, src/clanInventory/item/item.schema.ts, src/fleaMarket/dto/createFleaMarketItem.dto.ts, src/fleaMarket/dto/fleaMarketItem.dto.ts, src/fleaMarket/fleaMarketItem.schema.ts
This PR includes changes to the item properties and associated enums, objects, and methods. Most important changes involve renaming the QualityLevel to Rarity and new Material enum.
- `src/clanInventory/item/enum/qualityLevel.enum.ts` renamed to `rarity.enum.ts` and updated enum name from `QualityLevel` to `Rarity`.
- Added a new `Material` enum to represent item materials.
- Updated item schemas and DTOs to replace `qualityLevel` with `rarity` and to include `material` as a new property.
- Updated item names in `ItemName` enum for consistency, such as renaming `FLOORLAMP_RAKKAUS` to `LAMP_RAKKAUS`.
- Modified test files to reflect the changes in item props and names.
=> Created clan shop items list

src/clanShop/clanShop.controller.ts, src/clanShop/clanShop.module.ts, src/fleaMarket/fleaMarket.controller.ts, src/fleaMarket/fleaMarket.module.ts
Added "shop" permission validation for _/clan-shop/buy_ POST, _/fleaMarket/sell_ POST and _/fleaMarket/buy_ POST endpoints
- Added "Shop" right permission validation _/clan-shop/buy_ POST
- Added "Shop" right permission validation _/fleaMarket/sell_ POST
- Added "Shop" right permission validation _/fleaMarket/buy_ POST
- Fixed errors with Nest not being able to resolve clan and player models injections for `@HasClanRights()`
=> Added edit "shop" permission validation for all related endpoints

src/clan/clan.controller.ts
Added edit soul home permission validation for /clan PUT endpoint, which updates any clan data. Notice that logged-in player must also be in the updating clan.
- Added edit soul home permission validation for _/clan_ PUT endpoint
=> Added permission validation for edit clan data right for /clan PUT endpoint

src/__tests__/fleaMarket/FleaMarketService/handleSellItem.test.ts, src/__tests__/fleaMarket/modules/fleaMarketCommon.ts, src/__tests__/voting/data/voting/FleaMarketItemVotingBuilder.ts, src/__tests__/voting/data/voting/VotingDtoBuilder.ts, src/fleaMarket/fleaMarket.module.ts, src/fleaMarket/fleaMarket.service.ts, src/voting/dto/voting.dto.ts, src/voting/schemas/fleamarketItemVoting.schema.ts
Fixed bug with flea market selling endpoint can change the stock item price. Now item price is set only when the item is approved to be sold in the flea market.
- Changed price setting logic
- Fixed tests
=> Fixed bug with flea market selling endpoint can change the stock item price

src/box/box.module.ts, src/box/schemas/box.schema.ts, src/box/schemas/session.schema.ts, src/common/enum/modelName.enum.ts
Divide the box schema into box and session schemas.
- Add session schema and collection
- Move session related data from box to session schema
- Add session model to modelName enum
- Add session model to box module
=> add session schema and collection. Move session related props from box to session.

src/dailyTasks/enum/serverTaskName.enum.ts, src/fleaMarket/fleaMarket.controller.ts, src/fleaMarket/fleaMarket.module.ts
Add support for "suggest an item for the flea market sale" daily task.
- Emit a server event for daily task "SUGGEST_ITEM_TO_FLEA_MARKET"
=> Feature/add support for suggest an item for the flea market sale daily task 

src/player/player.controller.ts
Add support for "edit your avatar's appearance" daily task.
- Emit server event with CHANGE_AVATAR_OUTLOOK type if player.avatar objects changes
- Move event emitter code to a private method
=> Feature/add edit your avatar's appearance daily task 648

src/box/dto/boxName.dto.ts
Added a a new dto to be used later for new create box endpoint
=> Add box name dto
